#include "xy/xy.hpp"

#include "node.cpp"
#include "way.cpp"
#include "relation.cpp"
#include "tag.cpp"
#include "erase.cpp"
#include "get_trx_id.cpp"
#include "global.cpp"
#include "consume.cpp"
#include "clean.cpp"
#include "uid.cpp"
#include "owner.cpp"
