#include "xy/xy.hpp"

#include "node.cpp"
#include "way.cpp"
#include "relation.cpp"
#include "tag.cpp"
#include "erase.cpp"
#include "utils.cpp"
#include "on_notify.cpp"
#include "get_trx_id.cpp"
#include "global.cpp"
#include "consume.cpp"
#include "settings.cpp"
