#include "xy.hpp"

#include "global.cpp"
#include "node.cpp"
#include "way.cpp"
#include "relation.cpp"
#include "tag.cpp"
#include "clean.cpp"
#include "erase.cpp"
#include "bounds.cpp"
#include "get_trx_id.cpp"
